kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: todo-app

spec:
 replicas: 2
 selector:
   matchLabels:
      app: backend
 template:
   metadata:
      labels:
         app: backend

   spec:
     containers:
       - name: backend
         image: vibhutijain12/todo-backend:v1
         ports:
           - containerPort: 5000

         envFrom:
           - configMapRef:
                name: todo-config
           - secretRef:
                name: todo-db-secret

         readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5

         livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10

---

kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: todo-app

spec:
 selector:
   app: backend
 ports:
   - port: 5000
     targetPort: 5000
