kind: Service
apiVersion: v1
metadata:
  name: postgres        # <-- this name is the DNS hostname other pods use
  namespace: todo-app

spec:
  selector:
     app: postgres
  ports:
    - port: 5432
      targetPort: 5432
